package com.upao.biblioteca.domain.entity;

public enum Categoria {
    PROGRAMACION, BASEDEDATOS, REDES, SISTEMASOPERATIVOS, DISEÑO, INGENIERIA, MATEMATICA, FISICA, QUIMICA, BIOLOGIA, MEDICINA, ARTE, LITERATURA, HISTORIA, GEOGRAFIA, FILOSOFIA, PSICOLOGIA, ECONOMIA, POLITICA, DERECHO;
}
